# Generated by Django 4.1.1 on 2022-09-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('location', models.CharField(max_length=300)),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
