# Generated by Django 4.1.1 on 2022-09-19 20:06

from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_myuser_event_owner_alter_event_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=30, verbose_name='destination')),
                ('destinationIATA', models.CharField(max_length=12, verbose_name='destinationIATA')),
                ('origin', models.CharField(max_length=30, verbose_name='origin')),
                ('originIATA', models.CharField(max_length=12, verbose_name='originIATA')),
                ('type', models.CharField(max_length=15, verbose_name='type')),
                ('departure', models.DateTimeField(verbose_name='Departure')),
                ('arrival', models.DateTimeField(verbose_name='arrival')),
                ('created_at', models.DateField(default=hello.models.calc_date)),
            ],
        ),
    ]
