# Generated by Django 4.1.1 on 2022-09-19 20:55

from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.DateField(default=hello.models.calc_date, null=True),
        ),
    ]
